name: deployment

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout engine
        uses: actions/checkout@v2
        with:
          repository: thegeofront/engine
          path: engine

      - name: Build engine
        run: npm ci
        working-directory: ./engine

      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: app

      - run: npm ci
      - run: npm run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
